import TreeCertificateBatch001045N6
import TreeCertificateBatch011045N6
import TreeCertificateBatch021045N6
import TreeCertificateBatch031045N6
import TreeCertificateBatch041045N6
import TreeCertificateBatch051045N6
import TreeCertificateBatch061045N6
import TreeCertificateBatch071045N6
import TreeCertificateBatch081045N6
import TreeCertificateBatch091045N6
import TreeCertificateBatch101045N6
import TreeCertificateBatch111045N6
import TreeCertificateBatch121045N6
import TreeCertificateBatch131045N6
import TreeCertificateBatch141045N6
import TreeCertificateBatch151045N6

namespace Erdos1045N6.SixTree
set_option maxHeartbeats 0

theorem certificate_all_blocks : ∀ b : Fin 256, ∀ r : Fin 128,
    certificateCheck (BitVec.ofNat 15 (128*b.val+r.val)) = true := by
  intro b
  fin_cases b
  · exact certificate_block_0
  · exact certificate_block_1
  · exact certificate_block_2
  · exact certificate_block_3
  · exact certificate_block_4
  · exact certificate_block_5
  · exact certificate_block_6
  · exact certificate_block_7
  · exact certificate_block_8
  · exact certificate_block_9
  · exact certificate_block_10
  · exact certificate_block_11
  · exact certificate_block_12
  · exact certificate_block_13
  · exact certificate_block_14
  · exact certificate_block_15
  · exact certificate_block_16
  · exact certificate_block_17
  · exact certificate_block_18
  · exact certificate_block_19
  · exact certificate_block_20
  · exact certificate_block_21
  · exact certificate_block_22
  · exact certificate_block_23
  · exact certificate_block_24
  · exact certificate_block_25
  · exact certificate_block_26
  · exact certificate_block_27
  · exact certificate_block_28
  · exact certificate_block_29
  · exact certificate_block_30
  · exact certificate_block_31
  · exact certificate_block_32
  · exact certificate_block_33
  · exact certificate_block_34
  · exact certificate_block_35
  · exact certificate_block_36
  · exact certificate_block_37
  · exact certificate_block_38
  · exact certificate_block_39
  · exact certificate_block_40
  · exact certificate_block_41
  · exact certificate_block_42
  · exact certificate_block_43
  · exact certificate_block_44
  · exact certificate_block_45
  · exact certificate_block_46
  · exact certificate_block_47
  · exact certificate_block_48
  · exact certificate_block_49
  · exact certificate_block_50
  · exact certificate_block_51
  · exact certificate_block_52
  · exact certificate_block_53
  · exact certificate_block_54
  · exact certificate_block_55
  · exact certificate_block_56
  · exact certificate_block_57
  · exact certificate_block_58
  · exact certificate_block_59
  · exact certificate_block_60
  · exact certificate_block_61
  · exact certificate_block_62
  · exact certificate_block_63
  · exact certificate_block_64
  · exact certificate_block_65
  · exact certificate_block_66
  · exact certificate_block_67
  · exact certificate_block_68
  · exact certificate_block_69
  · exact certificate_block_70
  · exact certificate_block_71
  · exact certificate_block_72
  · exact certificate_block_73
  · exact certificate_block_74
  · exact certificate_block_75
  · exact certificate_block_76
  · exact certificate_block_77
  · exact certificate_block_78
  · exact certificate_block_79
  · exact certificate_block_80
  · exact certificate_block_81
  · exact certificate_block_82
  · exact certificate_block_83
  · exact certificate_block_84
  · exact certificate_block_85
  · exact certificate_block_86
  · exact certificate_block_87
  · exact certificate_block_88
  · exact certificate_block_89
  · exact certificate_block_90
  · exact certificate_block_91
  · exact certificate_block_92
  · exact certificate_block_93
  · exact certificate_block_94
  · exact certificate_block_95
  · exact certificate_block_96
  · exact certificate_block_97
  · exact certificate_block_98
  · exact certificate_block_99
  · exact certificate_block_100
  · exact certificate_block_101
  · exact certificate_block_102
  · exact certificate_block_103
  · exact certificate_block_104
  · exact certificate_block_105
  · exact certificate_block_106
  · exact certificate_block_107
  · exact certificate_block_108
  · exact certificate_block_109
  · exact certificate_block_110
  · exact certificate_block_111
  · exact certificate_block_112
  · exact certificate_block_113
  · exact certificate_block_114
  · exact certificate_block_115
  · exact certificate_block_116
  · exact certificate_block_117
  · exact certificate_block_118
  · exact certificate_block_119
  · exact certificate_block_120
  · exact certificate_block_121
  · exact certificate_block_122
  · exact certificate_block_123
  · exact certificate_block_124
  · exact certificate_block_125
  · exact certificate_block_126
  · exact certificate_block_127
  · exact certificate_block_128
  · exact certificate_block_129
  · exact certificate_block_130
  · exact certificate_block_131
  · exact certificate_block_132
  · exact certificate_block_133
  · exact certificate_block_134
  · exact certificate_block_135
  · exact certificate_block_136
  · exact certificate_block_137
  · exact certificate_block_138
  · exact certificate_block_139
  · exact certificate_block_140
  · exact certificate_block_141
  · exact certificate_block_142
  · exact certificate_block_143
  · exact certificate_block_144
  · exact certificate_block_145
  · exact certificate_block_146
  · exact certificate_block_147
  · exact certificate_block_148
  · exact certificate_block_149
  · exact certificate_block_150
  · exact certificate_block_151
  · exact certificate_block_152
  · exact certificate_block_153
  · exact certificate_block_154
  · exact certificate_block_155
  · exact certificate_block_156
  · exact certificate_block_157
  · exact certificate_block_158
  · exact certificate_block_159
  · exact certificate_block_160
  · exact certificate_block_161
  · exact certificate_block_162
  · exact certificate_block_163
  · exact certificate_block_164
  · exact certificate_block_165
  · exact certificate_block_166
  · exact certificate_block_167
  · exact certificate_block_168
  · exact certificate_block_169
  · exact certificate_block_170
  · exact certificate_block_171
  · exact certificate_block_172
  · exact certificate_block_173
  · exact certificate_block_174
  · exact certificate_block_175
  · exact certificate_block_176
  · exact certificate_block_177
  · exact certificate_block_178
  · exact certificate_block_179
  · exact certificate_block_180
  · exact certificate_block_181
  · exact certificate_block_182
  · exact certificate_block_183
  · exact certificate_block_184
  · exact certificate_block_185
  · exact certificate_block_186
  · exact certificate_block_187
  · exact certificate_block_188
  · exact certificate_block_189
  · exact certificate_block_190
  · exact certificate_block_191
  · exact certificate_block_192
  · exact certificate_block_193
  · exact certificate_block_194
  · exact certificate_block_195
  · exact certificate_block_196
  · exact certificate_block_197
  · exact certificate_block_198
  · exact certificate_block_199
  · exact certificate_block_200
  · exact certificate_block_201
  · exact certificate_block_202
  · exact certificate_block_203
  · exact certificate_block_204
  · exact certificate_block_205
  · exact certificate_block_206
  · exact certificate_block_207
  · exact certificate_block_208
  · exact certificate_block_209
  · exact certificate_block_210
  · exact certificate_block_211
  · exact certificate_block_212
  · exact certificate_block_213
  · exact certificate_block_214
  · exact certificate_block_215
  · exact certificate_block_216
  · exact certificate_block_217
  · exact certificate_block_218
  · exact certificate_block_219
  · exact certificate_block_220
  · exact certificate_block_221
  · exact certificate_block_222
  · exact certificate_block_223
  · exact certificate_block_224
  · exact certificate_block_225
  · exact certificate_block_226
  · exact certificate_block_227
  · exact certificate_block_228
  · exact certificate_block_229
  · exact certificate_block_230
  · exact certificate_block_231
  · exact certificate_block_232
  · exact certificate_block_233
  · exact certificate_block_234
  · exact certificate_block_235
  · exact certificate_block_236
  · exact certificate_block_237
  · exact certificate_block_238
  · exact certificate_block_239
  · exact certificate_block_240
  · exact certificate_block_241
  · exact certificate_block_242
  · exact certificate_block_243
  · exact certificate_block_244
  · exact certificate_block_245
  · exact certificate_block_246
  · exact certificate_block_247
  · exact certificate_block_248
  · exact certificate_block_249
  · exact certificate_block_250
  · exact certificate_block_251
  · exact certificate_block_252
  · exact certificate_block_253
  · exact certificate_block_254
  · exact certificate_block_255

#print axioms certificate_all_blocks
end Erdos1045N6.SixTree
